-- Qase PostgreSQL migration 001: identity and tenancy foundation.
-- UUID values are generated by the application so no database extension is required.

CREATE TABLE organizations (
	id uuid PRIMARY KEY,
	slug text NOT NULL,
	name text NOT NULL,
	status text NOT NULL DEFAULT 'active',
	created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at timestamptz,
	CONSTRAINT organizations_slug_format CHECK (slug ~ '^[a-z0-9][a-z0-9-]{0,62}$'),
	CONSTRAINT organizations_name_present CHECK (char_length(btrim(name)) BETWEEN 1 AND 200),
	CONSTRAINT organizations_status_valid CHECK (status IN ('active', 'suspended', 'deleted')),
	CONSTRAINT organizations_slug_unique UNIQUE (slug)
);

CREATE TABLE users (
	id uuid PRIMARY KEY,
	email text NOT NULL,
	normalized_email text NOT NULL,
	display_name text,
	status text NOT NULL DEFAULT 'active',
	created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at timestamptz,
	CONSTRAINT users_email_present CHECK (char_length(btrim(email)) BETWEEN 3 AND 254),
	CONSTRAINT users_normalized_email_valid CHECK (
		normalized_email = lower(btrim(normalized_email))
		AND char_length(normalized_email) BETWEEN 3 AND 254
	),
	CONSTRAINT users_display_name_valid CHECK (display_name IS NULL OR char_length(btrim(display_name)) BETWEEN 1 AND 200),
	CONSTRAINT users_status_valid CHECK (status IN ('active', 'suspended', 'deleted')),
	CONSTRAINT users_normalized_email_unique UNIQUE (normalized_email)
);

CREATE TABLE organization_memberships (
	organization_id uuid NOT NULL,
	user_id uuid NOT NULL,
	role text NOT NULL,
	status text NOT NULL DEFAULT 'active',
	created_by_user_id uuid,
	created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (organization_id, user_id),
	CONSTRAINT organization_memberships_organization_fk
		FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE RESTRICT,
	CONSTRAINT organization_memberships_user_fk
		FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
	CONSTRAINT organization_memberships_creator_fk
		FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE SET NULL,
	CONSTRAINT organization_memberships_role_valid CHECK (role IN ('owner', 'admin', 'developer', 'viewer')),
	CONSTRAINT organization_memberships_status_valid CHECK (status IN ('active', 'suspended'))
);

CREATE INDEX organization_memberships_user_lookup
	ON organization_memberships (user_id, status, organization_id);

CREATE TABLE projects (
	id uuid PRIMARY KEY,
	organization_id uuid NOT NULL,
	slug text NOT NULL,
	name text NOT NULL,
	status text NOT NULL DEFAULT 'active',
	created_by_user_id uuid,
	created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at timestamptz,
	CONSTRAINT projects_organization_fk
		FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE RESTRICT,
	CONSTRAINT projects_creator_fk
		FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE SET NULL,
	CONSTRAINT projects_slug_format CHECK (slug ~ '^[a-z0-9][a-z0-9-]{0,62}$'),
	CONSTRAINT projects_name_present CHECK (char_length(btrim(name)) BETWEEN 1 AND 200),
	CONSTRAINT projects_status_valid CHECK (status IN ('active', 'suspended', 'deleted')),
	CONSTRAINT projects_organization_id_unique UNIQUE (organization_id, id),
	CONSTRAINT projects_organization_slug_unique UNIQUE (organization_id, slug)
);

CREATE INDEX projects_organization_status_lookup
	ON projects (organization_id, status, updated_at DESC, id);
